# Generated by Django 3.2.15 on 2022-11-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_category_options'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking'),
            preserve_default=False,
        ),
    ]
